const getCommonEnv = (env) =>{
    return{
        REACT_APP_DOMAIN_NAME:env?.REACT_APP_DOMAIN_NAME,
        REACT_APP_DOMAIN_NAME:env?.REACT_APP_DOMAIN_NAME,
        REACT_APP_FAVICON:env?.REACT_APP_FAVICON,
        REACT_APP_MANIFEST_JSON:env?.REACT_APP_MANIFEST_JSON,
        REACT_APP_LOGO:env?.REACT_APP_LOGO,
        REACT_APP_LOGO_NAME:env?.REACT_APP_LOGO_NAME,
        REACT_USERNAME_TWITTER:env?.REACT_USERNAME_TWITTER,
        REACT_APP_STORE_ID:env?.REACT_APP_STORE_ID,
        REACT_ANDROID_PACKAGE:env?.REACT_ANDROID_PACKAGE,
        REACT_APP_NAME:env?.REACT_APP_NAME,
        REACT_USERNAME_TWITTER:env?.REACT_USERNAME_TWITTER,
    }
}
const Utils = {
    getCommonEnv:getCommonEnv
}
export default Utils;