/* eslint-disable react-hooks/rules-of-hooks */
import Head from 'next/head';
import React from 'react'
import { useSelector } from 'react-redux';

export default function login() {
    const donationBannerPosition = useSelector((state) => state?.allReducers?.donationBannerPosition);
    console.log("donationBannerPosition", donationBannerPosition)
  return (
    <div>
    <Head>
        <title>Login page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
